server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.217.66.65:8001/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
