server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/userdb
    username: postgres
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
