services:

  postgres:
    image: postgres
    container_name: postgres-db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  config-server:
    build:
      context: ./config-server

    image: config-server
    container_name: config-server

    ports:
      - "8888:8888"

    environment:
      CONFIG_REPO_LOCATION: file:/config-repo

    volumes:
      - ./config-repo:/config-repo:ro

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5


  user-service:
    image: user-service
    container_name: user-service

    ports:
      - "8081:8081"

    depends_on:
      postgres:
        condition: service_healthy

      config-server:
        condition: service_healthy
        
      service-registry:
        condition: service_started


  product-service:
    image: product-service
    container_name: product-service

    ports:
      - "8082:8082"

    depends_on:
      config-server:
        condition: service_healthy
        
      service-registry:
        condition: service_started


  api-gateway:
    build:
      context: ./api-gateway

    image: api-gateway
    container_name: api-gateway

    ports:
      - "8080:8080"

    depends_on:
      config-server:
        condition: service_healthy
        
      service-registry:
        condition: service_started
        
        
  service-registry:
    build:
      context: ./service-registry

    image: service-registry
    container_name: service-registry

    ports:
      - "8761:8761"        


    keycloak:
    image: quay.io/keycloak/keycloak:26.7.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: http://localhost:8090
    ports:
      - "127.0.0.1:8090:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  postgres-data:
  keycloak-data: 
