server:
  port: 8888
  address: 0.0.0.0

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/reza-mlk/spring-boot-microservices-demo.git
          default-label: main
          search-paths:
            - config-repo
          clone-on-start: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.5.244:8001/eureka/

  instance:
    prefer-ip-address: true